[package]
name = "coinmarketcap-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json","blocking","cookies"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
